name: Staging Pipeline
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - 'main'
env:
  AWS_ACCESS_KEY_ID: secret.AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: secret.AWS_SECRET_ACCESS_KEY
jobs:
  build-container:
    runs-on: ubuntu-latest
    needs: []
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup Environment
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=YOUR_ECR_REPO_NAME_HERE" >> $GITHUB_ENV
      - name: Build image
        run: |
          echo "building $ECR_REGISTRY/$ECR_REPOSITORY:latest"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
      - name: Push image to Amazon ECR
        run: |
          echo "pushing $ECR_REGISTRY/$ECR_REPOSITORY:latest"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
